backend:
  name: github
  repo: zotim4git/tripwithme    # 깃허브 user/repo
  branch: main
  base_url: https://tripwithme-nine.vercel.app
  auth_endpoint: api/auth

media_folder: "src/uploads"
public_folder: "/uploads"

collections:
  - name: "seoul"
    label: "Seoul"
    folder: "src/seoul_spot"
    create: true
    extension: "md"
   

    # 파일명 규칙 → slug 필드 값으로 파일 생성
    identifier_field: "slug"
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug (URL)"
        name: "slug"
        widget: "string"
        hint: "영어소문자-숫자-하이픈만 (예: seoul-sungbuk-cafe)"
        pattern: ['^[a-z0-9-]+$', '영어 소문자/숫자/하이픈(-)만 가능']

      - label: "City"
        name: "city"
        widget: "hidden"
        default: "seoul"

      - label: "Main Image"
        name: "main_image"
        widget: "image"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
        
        
  - name: "tokyo"
    label: "Tokyo"
    folder: "src/tokyo_spot"
    create: true
    extension: "md"

    identifier_field: "slug"
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug (URL)"
        name: "slug"
        widget: "string"
        hint: "영어소문자-숫자-하이픈만 (예: tokyo-cafe)"
        pattern: ['^[a-z0-9-]+$', '영어 소문자/숫자/하이픈(-)만 가능']

      - label: "City"
        name: "city"
        widget: "hidden"
        default: "tokyo"

      - label: "Description"
        name: "description"
        widget: "text"
        
      - label: "Location Group"
        name: "location_group"
        widget: "select"
        options:
          - { label: "1", value: "1" }
          - { label: "2", value: "2" }
          - { label: "3", value: "3" }
          - { label: "4", value: "4" }

      - label: "Location Text"
        name: "location_text"
        widget: "string"
        required: false

      - label: "Main Image"
        name: "main_image"
        widget: "image"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"